### ISSUE TITLE
Описать на вики диаграмму классов, обеспечивающих работу с R

### ISSUE THREAD

**Issue by adavydenko** [lanit-tercom-school/analyzeme#102]

**Comment by lagroffe** [comment]
Также дополнить статью о способах интеграции с R, см. используемое в #91

**Comment by lagroffe** [comment]
\+ добавить страницу о правилах написания скрипта

**Comment by lagroffe** [comment]
дополнение к статье о способах интеграции - о [Renjin](https://github.com/lanit-tercom-school/analyzeme/wiki/Renjin-%28R-in-JVM%29)

**Comment by lagroffe** [comment]
диаграммы классов интеграции на [wiki](https://github.com/lanit-tercom-school/analyzeme/wiki/R-integration-architecture)

**Comment by lagroffe** [comment]
[Страница о правилах написания скриптов](https://github.com/lanit-tercom-school/analyzeme/wiki/R-scripts)

**Comment by lagroffe** [comment]
Требуемые страницы и диаграммы реализованы. Есть вопрос по поводу диаграмм классов, отвечающих за интеграцию. Достаточно только диаграмм классов, или привести пару примеров их взаимодействия?

**Comment by adavydenko** [comment]
Спасибо. Я думаю, что диаграмм классов достаточно. Лучшим примером демонстрации будут юнит тесты на функциональность. Их будет более чем достаточно.

**Comment by lagroffe** [comment]
Для непосредственно интеграции есть, для фасада и оберток постепенно добавлю

**Comment by adavydenko** [comment]
Ок, тогда на текущий момент должно быть достаточно. Задачу на разработку интеграционных тестов нужно обсудить и добавить в виде отдельной issue - т.к. она займет существенное время. Сейчас делать этого не нужно.

**Comment by lagroffe** [comment]
Хорошо, про интеграционные тогда напомню на собрании
