### ISSUE TITLE
Создать окно выбора файла

### ISSUE THREAD

**Issue by adavydenko** [lanit-tercom-school/analyzeme#11]
Необходимо разработать страницу, обеспечивающую загрузку файлов с клиентам на сервер.
~~В качестве поддерживаемых файлов, должны выступать файлы с расширением .xls/.xlsx~~

**Comment by adavydenko** [comment]
Решили реализовать в виде popup-а на стартовой странице.

**Comment by Skipper04** [comment]
Страничка разработана.
