### ISSUE TITLE
Описать архитектуру анализаторов

### ISSUE THREAD

**Issue by adavydenko** [lanit-tercom-school/analyzeme#116]
Продумать и описать диаграмму классов (на вики), реализующих функции анализа.
Предполагаем, что анализаторы бывают следующих видов:

1. Возвращает скалярный результат 
1. Точка на графике (предполагаем, что хотим локализовать уже существующие данные, напр. выделить точку другим цветом)
1. Набор точек

В рамках данной задачи - придумать/переиспользовать сущестующие анализаторы для иллюстрации каждого из случаев

**Comment by olga-muravjova** [comment]
[статья на wiki про анализаторы](https://github.com/lanit-tercom-school/analyzeme/wiki/Analyzers-%28version-2%29)

**Comment by adavydenko** [comment]
Возвращать строку не очень хорошо, т.к. с ней потом ничего не сделать.
Рассмотрите возможность возвращать кастомный результат, который в свою очередь может быть приведен к JSON-представлению.

**Comment by lagroffe** [comment]
Пытались его обсуждать пару недель назад, тогда остановились на строке. А что этот кастомный результат может из себя представлять? Просто обёртка для одного из возможных возвращаемых значений? Как один класс для всех них, как реализации одного интерфейса или как получится?

**Comment by adavydenko** [comment]
В зависимости от того, что именно будет возвращать анализатор - это может быть либо скаляр, либо набор скаляров (ассоциативный массив), либо массив  ну и т.д.
Возвращать строку конечно же можно, но я имел в виду, что строку _можно_ пробрасывать вызывающему объекту в виде json.
Но это не означает, что анализатор должен возвращать именно json :).

Можно сделать, например так:
```java
T result = new MyAnalyzer<T>().Analyze(input);
return result.toJSON();
//...
```

**Comment by lagroffe** [comment]
Ок, тогда частично вернёмся к предыдущему варианту.
У нас ведь не будет аналайзеров, которые гипотетически возвращают значения разных типов в зависимости от того, что у них получилось?

**Comment by adavydenko** [comment]
Нет, наверное таких не будет.
По поводу возвращаемого результата, моя идея стороится на следующих принципах:

1. аналайзер на входе/выходе должен оперировать абстракциями одного порядка (если принимает double, то и возвращает стандартный тип, если принимает json - то его же и возвращает). Это почти как уровни стэка протоколов. Плюсом такого подхода - простота тестирования
1. У класса должно быть только одно назначение (SOLID принцип), он не должен заниматься и расчетом и конвертированием

**Comment by lagroffe** [comment]
Хорошо, тогда если совсем выносить из аналайзера конвертацию и оставлять тип возвращаемого значения явным, работа с ними будет выглядеть как-то так (сейчас в ветке Analyzers).
```java
//List<DataSet> data came here from other place
List<Point[]> points = new ArrayList<Point[]>();
for(DataSet set : data) {
	points.add(set.getPoints());
}
IAnalyzer myAnalyzer = AnalyzerFactory.getAnalyzer("sth");
SomeTypeOfReturnValue result = myAnalyzer.analyze(points);
```
