### ISSUE TITLE
Проработать архитектуру классов источников данных

### ISSUE THREAD

**Issue by adavydenko** [lanit-tercom-school/analyzeme#118]
Продумать архитектуру классов, представляющих из себя источники данных.
Считаем, что файл - такой же источник.

**Comment by lagroffe** [comment]
[страница](https://github.com/lanit-tercom-school/analyzeme/wiki/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B---%D0%B8%D1%81%D1%82%D0%BE%D1%87%D0%BD%D0%B8%D0%BA%D0%B8-%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85)

**Comment by lagroffe** [comment]
[статья о добавлении нового источника данных](https://github.com/lanit-tercom-school/analyzeme/wiki/%D0%94%D0%BE%D0%B1%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BD%D0%BE%D0%B2%D0%BE%D0%B3%D0%BE-%D0%B8%D1%81%D1%82%D0%BE%D1%87%D0%BD%D0%B8%D0%BA%D0%B0-%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85)
