### ISSUE TITLE
Выбрать контрол для загрузки файлов

### ISSUE THREAD

**Issue by adavydenko** [lanit-tercom-school/analyzeme#12]
Необходимо рассмотреть возможные варианты и выбрать js библиотеку для загрузки файлов (в рамках задачи #11). Опубликовать страницу на вики со списком рассмотренных вариантов и привести пример использования.

**Comment by adavydenko** [comment]
а где опубликованная страничка? )

**Comment by olga-muravjova** [comment]
https://github.com/lanit-tercom-school/analyzeme/wiki/What-is-Servlet%3F
