### ISSUE TITLE
Репозиторий зарегистрированных обработчиков

### ISSUE THREAD

**Issue by adavydenko** [lanit-tercom-school/analyzeme#120]
Нужен список зарегистрированных в системе обработчиков R.
Предусмотреть 3 типа:
* FakeR
* Rserve
* Renjin

Для каждого из обработчиков нужно хранить/редактировать персональные настройки (см #119)

Добавить наполнение репозитория по-умолчанию.

**Comment by SKutukov** [comment]
Добавлена  диаграмма репозитория https://github.com/lanit-tercom-school/analyzeme/wiki/RConfiguration

**Comment by adavydenko** [comment]
Добавьте краткое описание назначения каждого из классов и возможно пример использования. Я не понял как он будет использоваться и как эти 2 диаграммы взаимосвязаны между собой.

**Comment by lagroffe** [comment]
Для RScriptManager (наверное это всё-таки лучше добавить прямо в Conf, чтобы не хранить конфигурации дважды), нужны: boolean поле свободен ли сейчас (по умолчанию true) и boolean - установлено ли соединение (по умолчанию false). //"установлено ли соединение" отличается от activeFlag, если что.
Плюс статическое поле для каждого вида конфигураций отдельно - boolean поддерживает ли многопоточность.

Ещё в репозитории нужна функция, которая позволяет получить случайный  доступный обработчик (доступный, т.е. activeFlag и поле свободен ли - true). Тут, наверное, нужно отделить Rserve+Renjin от FakeR из-за разных результатов выполнения - что-то вроде ~`getFreeRConf` и ~`getFreeTestRConf`.
На случай, если она не отработала - ~`getActiveRConf` и ~`getActiveTestRConf`- идея та же, но true только active. 
//вкладывать одну в другую не надо

Плюс позже могут понадобиться функции для получения обработчика с другим набором true-флагов, но пока необязательны. Мб всё это можно объединить в одну функцию с параметрами специального вида, как удобнее, лишь бы можно было вызвать.

**Comment by adavydenko** [comment]
А зачем у RScriptManager новое поле?Если на случай проверки возможности запуска скриптов, то тогда лучше предусмотреть специальный результат, мол, "сейчас занят, не могу обрабоать запрос". Т.е. клиент должен попросить Менеджер выполнить запрос и обработать результат.

Переносить на вызывающую сторонку логику проверки, занят ли менеджер или нет, думаю не стоит. Это усложнит логику клиента.

**Comment by lagroffe** [comment]
Нет, я не это предлагаю, я предлагаю добавить в репозиторий, который хранит сведения о конфигурации, эту отметку - вернее, в сами эти сведения. Мы же хотим, например, отображать таблицу тех, кто сейчас что-то делает, она все равно пригодится.
Это будет служебное поле скрипт-менеджера - просто чтобы не дублировать список используемых обработчиков он будет делать свои пометки прямо в репозитории. Со стороны клиента не изменяется, только скриптменеджер смотрит на них перед запуском скрипта.
А ещё "отвечать" никто из текущих средств интеграции самостоятельно не будет, они будут просто в очередь добавлять скрипт, что в случае чего-то крупного может затянуться.

**Comment by adavydenko** [comment]
Поле лучше не добавлять, т.к. кто-то должен его синхронизировать.
До тех пор, пока оно явно нам не требуется, признак активности можно вычислять по наличию заданий в очереди.

**Comment by lagroffe** [comment]
Да, скрипт-менеджер, потому что его и не будет использовать никто, кроме скрипт-менеджера. Но, по-моему, это будет проще обсудить на собрании, ладно.
