### ISSUE TITLE
UI для управления R-обработчиками

### ISSUE THREAD

**Issue by adavydenko** [lanit-tercom-school/analyzeme#122]
1. Нужно реализовать jsp страницу (Spring.MVC), которая в качестве контроллера будет использовать #121.
1. На форме должны быть функции добавления/удаления/редактирования.
1. Форма должна быть доступна из главного меню.

**Comment by SKutukov** [comment]
Доделать:
1)Единые шрифты в формочках;
2)Поля для обновления в формочках перенести налево
3)Выставить звездочки напротив полей, обязательных для заполнения
4)Колонку Using Port и Using Host объединить в Settings

**Comment by SKutukov** [comment]
Необходимые доработки вынесены в задачу #180
