### ISSUE TITLE
Линейный коэффициент корреляции

### ISSUE THREAD

**Issue by olga-muravjova** [lanit-tercom-school/analyzeme#129]
Разработать анализатор для нахождения линейного коэффициента корреляции
(и всех необходимых для этого статистик)
См. [страницу на Wiki](https://github.com/lanit-tercom-school/analyzeme/wiki/%D0%9B%D0%B8%D0%BD%D0%B5%D0%B9%D0%BD%D1%8B%D0%B9-%D0%BA%D0%BE%D1%8D%D1%84%D1%84%D0%B8%D1%86%D0%B8%D0%B5%D0%BD%D1%82-%D0%BA%D0%BE%D1%80%D1%80%D0%B5%D0%BB%D1%8F%D1%86%D0%B8%D0%B8)

**Comment by adavydenko** [comment]
Нужно описать и поставить ссылки на вики, как вычислять указанные статистики.
