### ISSUE TITLE
Реализовать хранилище файлов на сервере

### ISSUE THREAD

**Issue by adavydenko** [lanit-tercom-school/analyzeme#13]
В рамках задачи #11 необходимо реализовать хранилище файлов на стороне сервера. Реализация должна включать следующие задачи:
1. Разработать архитектуру классов для доступа к файлам:
 * Сохранение новых файлов
 * Получение файлов по ключу
 * Получение информации о загруженном файле.
2. Реализовать класс-хранилище на диске
3. ~~Реализовать класс-хранилище в RAM в виде ассоциативного массива (будет использоваться в тестах)~~ Обеспечить покрытие юнит-тестами - см. #36

Пример использования:
```java
Part part = getPartFromRequest();
IFileRepository repository = GetRepository();
FileToken token = repository.Persist(part);
//....
File file = repository.getFileByToken(token);
FileToken[] allFiles = repository.GetAllFiles();
```

**Comment by lagroffe** [comment]
структура хранилища см. [wiki](https://github.com/lanit-tercom-school/analyzeme/wiki/File-Repository)

**Comment by lagroffe** [comment]
Хранилище не работает с удалённым сервером. Вероятные проблемы:
1. Неверно обрабатывается appPath, извлекаемая из реквеста.
2. Нет прав на создание папки/запись файлов на сервер.
3. ?

**Comment by adavydenko** [comment]
2 выглядит наиболее вероятным. Чтобы разобраться, необходимо реализовать логирование операция и ошибок на сервере.
Мне кажется, если бы возникло исключение, то базовый контроллер выкинул бы какое-нибудь сообщение об ошибке пользователю.

**Comment by lagroffe** [comment]
На данный момент есть разве что это: 
2015-12-07T20:13:42.798221+00:00 heroku[router]: at=info method=GET path="/Upload.jsp" host=analyzeme-dev.herokuapp.com request_id=140d1d30-25d4-45f9-b5aa-281ca490f634 fwd="217.197.0.142" dyno=web.1 connect=1ms service=2ms status=200 bytes=3840
2015-12-07T20:14:36.145304+00:00 heroku[router]: at=info method=POST path="/UploadServlet" host=analyzeme-dev.herokuapp.com request_id=7c080c7c-aef0-45e4-a625-233dea10d219 fwd="217.197.0.142" dyno=web.1 connect=2ms service=266ms status=200 bytes=179
