### ISSUE TITLE
Уравнение линейной регрессии

### ISSUE THREAD

**Issue by olga-muravjova** [lanit-tercom-school/analyzeme#130]
Разработать анализатор для нахождения коэффициентов уравнения линейной регрессии
См. [страницу на Wiki](https://github.com/lanit-tercom-school/analyzeme/wiki/%D0%A3%D1%80%D0%B0%D0%B2%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BB%D0%B8%D0%BD%D0%B5%D0%B9%D0%BD%D0%BE%D0%B9-%D1%80%D0%B5%D0%B3%D1%80%D0%B5%D1%81%D1%81%D0%B8%D0%B8)

**Comment by adavydenko** [comment]
Нужно описать и поставить ссылки на вики, как вычислять указанные статистики.
