### ISSUE TITLE
Анализ временных рядов 

### ISSUE THREAD

**Issue by olga-muravjova** [lanit-tercom-school/analyzeme#131]
Разработать анализатор для выявления компонент временного ряда
См. [страницу на Wiki](https://github.com/lanit-tercom-school/analyzeme/wiki/%D0%90%D0%BD%D0%B0%D0%BB%D0%B8%D0%B7-%D0%B2%D1%80%D0%B5%D0%BC%D0%B5%D0%BD%D0%BD%D1%8B%D1%85-%D1%80%D1%8F%D0%B4%D0%BE%D0%B2)
- [x] Дополнить статью описаниями методов необходимости
- [x] Описать в статье используемые определения
- [x] Расчет тренда - описать анализатор на вики (4 метода)
- [x] Реализация анализаторов (java class)
- [x] Расчет тренда - реализация
- [x] Расчет сезонной компоненты - описать анализтор на вики
- [x] Расчет сезонной компоненты - реализация
- [x] Расчет остатков - описать анализатор на вики
- [x] Расчет остатков - реализация

**Comment by adavydenko** [comment]
Нужно описать и поставить ссылки на вики, как вычислять указанные статистики.

**Comment by lagroffe** [comment]
Кстати, т.к. методы здесь просто не будут работать с нынешними "демо-данными", хорошо бы добавить пример таких, которые будут давать какой-то результат.

**Comment by PonizovaV** [comment]
ОК. Только не могу сориентироваться, где эти "демо-данные" сейчас находятся.
