### ISSUE TITLE
Форма настроек для Rserve

### ISSUE THREAD

**Issue by adavydenko** [lanit-tercom-school/analyzeme#134]
Реализовать диалог для задания настроек Rserve:
 - Наименование
 - Статус (=true by default)
 - host (url)
 - port

**Comment by SKutukov** [comment]
Сама формочка сделана.Работа с сервером после закрытия формы считается частью задачи #122.

**Comment by adavydenko** [comment]
Тогда допишите в #122 что именно нужно доделать.
Сохранение настроек на сервере должно производиться из данный формы, а не другой.
