### ISSUE TITLE
Описать на wiki таблицу URL-запросов

### ISSUE THREAD

**Issue by adavydenko** [lanit-tercom-school/analyzeme#136]
Добавить на вики страницу с описанием всех поддерживаемых URL-адресов.

**Comment by lagroffe** [comment]
[страница](https://github.com/lanit-tercom-school/analyzeme/wiki/URL)

**Comment by adavydenko** [comment]
Отлично. Попробуйте переформатировать, чтобы на страницу помещалась (по ширине). Может быть количество столбцов убрать или писать в виде `GET: /projects/`

**Comment by lagroffe** [comment]
отражены [изменения](https://github.com/lanit-tercom-school/analyzeme/wiki/URL) по #140.
по поводу ширины таблицы - немного объединила плюс раздробила url, не знаю, насколько лучше.

**Comment by lagroffe** [comment]
Все явные проблемы с URL устранены (см. #140), таблица им соответствует
