### ISSUE TITLE
Исправить контроллеры

### ISSUE THREAD

**Issue by lagroffe** [lanit-tercom-school/analyzeme#140]
Найденные проблемы по #136:
*  ~~FileController at `/upload/{user_id}/{project_id}` на самом деле использует username~~
* ~~AnalysisController at `/file/{file_name}/data` возвращает файл дважды: в responseText и под header Data~~
* ~~AnalysisController at `/file/{file_name}/{function_Type}` в response text зачем-то возвращает 1~~
* ~~ProjectsController  не подразумевает разделения на пользователей~~
* ~~ProjectsController at `/project/{project_name}/files` работает с projectName вместо projectId~~

**Comment by olga-muravjova** [comment]
Беру на себя исправить это, если ты не против
