### ISSUE TITLE
В окне для редактирования кода read-only  сегмент кода можно убрать с помощью Ctrl+Z

### ISSUE THREAD

**Issue by SKutukov** [lanit-tercom-school/analyzeme#142]
В окне для редактирования кода (#64)  read-only  сегмент кода можно убрать с помощью Ctrl+Z.
При этом ввести что еще не получиться, так как сегмент доступен только для чтения.

**Возможное решение**:вносить первоначальный код средствами html, а не ace-editor.

**Comment by adavydenko** [comment]
надо проверить, как добавляется фрагмент. Возможно при вставке данная операция сохраняется в буфере и поэтому ее можно отменить. Необходимо проверить, есть ли фозможность "фиксировать" состояние, либо обрабатывать ctrl-z самостоятельно.

**Comment by maxim-yakupov** [comment]
Вроде уже не актуально
