### ISSUE TITLE
Список уникальных имен проектов пользователя позволяет иметь повторения

### ISSUE THREAD

**Issue by maxim-yakupov** [lanit-tercom-school/analyzeme#143]
В [вики](https://github.com/lanit-tercom-school/analyzeme/wiki/URL)(#136) указано, что по `/user/project` получаем список уникальных для пользователя имен. Однако, при создании нескольких проектов с одинаковыми именами возвращается список из одинаковых имен. Т.е. не выполняется, что каждое имя уникально, а также, если верить той же вики-странице, для удаления проекта используется это самое уникальное имя, однако на самом деле там используется `projectId`. 

Нужно исправить либо вики, либо контроллеры(#140)

**Comment by lagroffe** [comment]
Для удаления используется projectId. Просто раньше имена проектов тоже не могли повторяться, я забыла, что это недавно убрали - "уникальное" в другом смысле использовалось)

Возможно, есть смысл в таске на приведение всех url к одному виду, это да. Одно и то же в них часто названо по-разному.
Пока поменяла в вики на "идентификатор" то, что подразумевалось как projectId + про имена /user/project поправила.
(а зачем вообще используется этот контроллер, когда есть возвращающий информацию о проектах? Он нужен?)

**Comment by maxim-yakupov** [comment]
Нет, не нужен, просто подумал, раз что-то новое, то под него переделывать будете. 

Раз уж у нас вводится UserID, то неплохо бы сделать выдачу проектов(как по `/projects/info`) отдельного пользователя. Ну и вставить бы его в информацию о проекте, или заменить поле логин на айди, либо прямо в поле логин его прописывать.
