### ISSUE TITLE
Неправильная обработка загрузки файлов в проект

### ISSUE THREAD

**Issue by maxim-yakupov** [lanit-tercom-school/analyzeme#145]
Если у нас имеется несколько проектов с одинаковым именем, то все файлы, загруженные в любой из них, будут принадлежать первому созданному.

Например, создаем проект с id = project_1 и name = "new", и еще один: id = project_2 и name = "new". Теперь, в какой бы из этих проектов мы ни загружали файлы, список файлов для проекта с id = project_2 будет пуст, и эти файлы добавятся к файлам проекта с id = project_1.

Это серьезный баг, ибо можно удалить первый из проектов с одинаковым именем, и тогда при загрузке в остальные проекты мы потеряем возможность хоть откуда-то получить список файлов(по сути, такие проекты становятся чисто демо-проектами).

**Comment by maxim-yakupov** [comment]
https://github.com/lanit-tercom-school/analyzeme/commit/54f15c692bbf377379608a4d17d1dc556a9bc837#diff-98a831519e994b4ca6fcde6a625ece00R34

**Comment by maxim-yakupov** [comment]
https://github.com/lanit-tercom-school/analyzeme/blob/54f15c692bbf377379608a4d17d1dc556a9bc837/src/main/java/com/analyzeme/controllers/FileController.java#L48

Здесь файл приписывается не к id проекта, а к названию, отсюда и проблемы. Думаю, пофиксить будет не сложно, но лезть не буду, чтобы что-нибудь не сломать.

**Comment by maxim-yakupov** [comment]
В принципе, это продолжение #140

**Comment by lagroffe** [comment]
В первой версии всё загружалось по именам - пользователя, проекта и т.п. Когда переводили на новую версию, видимо, не посмотрели, что для projectId другая функция. Я поправила её сразу и на projectId и userId. 
Сейчас, вроде бы, всё норм?

**Comment by maxim-yakupov** [comment]
Сейчас да
