### ISSUE TITLE
REditorComponent

### ISSUE THREAD

**Issue by adavydenko** [lanit-tercom-school/analyzeme#150]
Angular2 Component, позволяющий редактировать R скрипты пользователем при помощи Ace-редактора.
Содержит комбобокс с выбором типа возвращаемого значения и кнопку Run.

**Comment by lagroffe** [comment]
Скрипты, возвращающие double, работают. Скрипты, возвращающие точки/точку/строку выкидывают ассортимент ошибок 406, 409 или 500. При этом когда я проверяю те же скрипты на существующем временном API, они работают.

Для скрипта для точек, например, проблема видимо в переводе в json: com.fasterxml.jackson.databind.JsonMappingException: No serializer found for class com.analyzeme.analyze.Point and no properties discovered to create BeanSerializer
Плюс - в том, что R работает с немного другими точками из analyze и возвращает их (самый простой способ поправить - сделать те точки реализацией новго, общего с из analyzers, интерфейса и использовать в IResult его).

Другие, кроме строки, думаю, аналогично.

**Comment by maxim-yakupov** [comment]
Так а как это к REditorComponent относится? Обеспечение бэкенда это же отдельная задача, хоть и связанная.
