### ISSUE TITLE
Обсудить список проектов

### ISSUE THREAD

**Issue by maxim-yakupov** [lanit-tercom-school/analyzeme#159]
Решить какой список проектов использовать: projects.jsp или ProjectPageComponent(компонент Angular приложения). Определиться, убирать ли из кода лишний список проектов или оставить к нему какой-либо альтернативный доступ.

**Comment by adavydenko** [comment]
Когда будете обсуждать, опишите общий вид приложения желательно с картинками), в случае, если будет оставлять в angular приложении.

**Comment by maxim-yakupov** [comment]
Так общий вид то давно готов.
Текущая страница проектов: ![Текущая страница проектов](https://cloud.githubusercontent.com/assets/6084714/14751716/f1b9875e-08d3-11e6-8cbf-29eda5321335.png)
Ангулярная: 
![Ангулярная страница проектов](https://cloud.githubusercontent.com/assets/6084714/14751756/2b86f958-08d4-11e6-888e-d8556af94d61.png)

По-моему, выбор очевиден :)

**Comment by adavydenko** [comment]
В ангулярной версии изменить:

1. Список проектов перенести в левую часть экрана
1. Сделать master-detail, при выборе проекта - отображается детальная информация в правой части на панели.

**Comment by adavydenko** [comment]
1. Обсудили на встрече 28.04: оставляем проекта на angular и старую форму.
2. Форму проектов на angular доработать в соответствии с комментарием выше
