### ISSUE TITLE
Удаление источников данных (файлов)

### ISSUE THREAD

**Issue by adavydenko** [lanit-tercom-school/analyzeme#170]
Необходимо обеспечить поддержку удаления файлов в рамках проекта:

1. Удалять можно только файлы, загруженные в рамках проекта. Т.о. удаление - деактивация ранее подключенных источников
  * В файле есть атрибут `isActive`: `false` - уже удален, `true` - доступен. При удалении файла - необходимо проставлять флаг в `false`
  * HTTP GET запросы должны возвращать только _активные_ файлы (`isActive=true`)
  * `isActive` не возвращается через `json`
1. ПРОВЕРИТЬ: Обертка над рест-констроллером в Angular - готово
1. ПРОВЕРИТЬ: В списке файлов отображать пиктограмму удаления. При нажатии - открывается модальное окно с подверждением удаления.
1. После удаления файл исчезает из списка на веб-форме - готово

**Comment by lagroffe** [comment]
Когда появятся новые типы источников данных, мы собираемся держать их в том же списке и, соответственно, "удалять" запросом на тот же контроллер, или они будут где-то отдельно? (вопрос влияет скорее на #118, но тут ближе по теме)

**Comment by adavydenko** [comment]
Хороший вопрос. Мне видится это так:
1. Существуют поставщики данных (напр. портал открытых данных)
2. Они предоставляют инстансы данных (напр. данные по земельным участкам за определенный период)
3, Инстансы данных подключаются к проектам.

В таком виде, в зависимости от того, является ли инстанс специфическим для проекта, или общим для группы проектов (как бы расшаренный), то мы его либо удаляем, либо исключаем из списка проектов.

Отвечая на Ваш вопрос, давайте удалять [пока].

**Comment by lagroffe** [comment]
Хорошо, я тогда добавлю новый метод к DataSet и удаление/отключение будет происходить через него, чтобы это и для других источников работало.

**Comment by adavydenko** [comment]
Ммм.. может быть лучше добавить этот метод к проекту - removeDataSet?
В любом случае, когда удаляется источник данных, необходимо также и удалять связ между проектом и этим источником (она ведь навернякак где-то у нас есть..?)

**Comment by lagroffe** [comment]
Связь есть, но она пока немного односторонняя - про свои файлы проект знает (ProjectInfo и др.осталась с тех пор, когда были только файлы), про другие источники - нет. А вот dataset при формировании может знать о чём угодно, в зависимости от того, как реализован класс, который его создаёт. Для него пока предполагалась только возможность получать данные для анализа/отображения.

Т.е. нет какого-то общего места, которое объединяет все datasetы для пользователя или проекта, они использовались только с условием, что известен одновременно тип источника и идентификатор, формировались на ходу для получения нужных данных в стандартном формате.

Если представлять все источники одним списком, скорее всего есть смысл поменять в ProjectInfo список идентификаторов на коллекцию датасетов ([нынешние репозитории](https://cloud.githubusercontent.com/assets/8055513/14330920/7a3b5dc2-fc4b-11e5-9b6f-66c0945216b1.png), если что), добавить к датасету метод для деактивации, и тогда уже сделать внешний метод для проекта removeDataSet(). Но это займёт достаточное количество времени, projectsRepository почти все методы придётся переписать.
Этим заниматься, или пока оставить чисто для файлов, как сейчас, а остальное поменять попозже при появлении других источников?

**Comment by adavydenko** [comment]
Нет, если много времени займет, то сейчас менять не нужно. Пусть остаются только файлы.
На встрече (в четверг 04.05) обсудим/проработаем как будет все выглядеть в перспективе.

**Comment by lagroffe** [comment]
TODO:
1. FileInfo сейчас появляется только по двойному клику
2. Скрывать удалённый файл без обновления страницы

Нужно обсудить, есть ли необходимость выносить FileInfo в отдельный компонент или можно добавить скролл FileListу и оставить как есть

**Comment by adavydenko** [comment]
По поводу диаграммы репозиториев. Нужно будет провести небольшой рефакторинг:
- либо переименовать IRepository -> IUsersRepository (для единообразия)
- либо если IRepository предполагается общим интерфейсом, то сделать его базовым для IFileRepository и ProjectsRepository

**Comment by lagroffe** [comment]
суть его названия была немного не в этом: в том, что это общий интерфейс для репозиториев именно того уровня, что и UsersRepository (там были варианты про то, что появятся репозитории для аватарок и ещё чего-нибудь в будущем) - как здесь на последней схеме. но если мы совсем не планируем их добавлять, тогда пусть будет IUsersRepository.

![](https://cloud.githubusercontent.com/assets/8055513/13224829/5f400af4-d99b-11e5-9090-418c1f2a58b5.png)

**Comment by adavydenko** [comment]
Решили пока в репозиториях ничего не менять. После проведем код-ревью и рефакторинг репозиториев.

**Comment by lagroffe** [comment]
Выделено #196
