### ISSUE TITLE
Описать структуру Angular-проекта

### ISSUE THREAD

**Issue by adavydenko** [lanit-tercom-school/analyzeme#171]
Добавить в [Project-structure](https://github.com/lanit-tercom-school/analyzeme/wiki/Project-structure) описание (и правила) структрктуры исходных кодов Angular приложения.

**Comment by maxim-yakupov** [comment]
https://github.com/lanit-tercom-school/analyzeme/wiki/Project-structure/c96e8e841282d72d3a6cecfbb2e39c88da4ef0aa

**Comment by adavydenko** [comment]
Надо обновить картинку

**Comment by maxim-yakupov** [comment]
Обновлено
