### ISSUE TITLE
Добавить интеграцию с codebeat/аналогом

### ISSUE THREAD

**Issue by adavydenko** [lanit-tercom-school/analyzeme#175]
https://codebeat.co/

**Comment by lagroffe** [comment]
`Unsupported project`
Codebeat currently supports analysis of Swift, Go and Ruby codebases. This message may show up if the selected repository contains zero supported files. We are working to add support for Objective-C and Java in Q2 2016.

**Comment by lagroffe** [comment]
Codacy
