### ISSUE TITLE
Изменить навигацию по сайту

### ISSUE THREAD

**Issue by adavydenko** [lanit-tercom-school/analyzeme#181]
Выделить открытую часть сайта и приложение.

зачёркнуто сделанное
**Меню стартовой страницы:**
~~Home -> ./index~~
~~Try Now -> ./app/demo~~
~~Configration -> /config~~
~~Preview -> ./data/spb/...~~

**Меню angular приложения**
~~Projects -> ./app/projects~~
~~./app/projects/{id}~~
~~./app/projects/{id}/plot~~
~~./app/projects/{id}/redit~~
 ~~AnalyzeMe~~ (snap to right)

 ~~В рамках данной задачи дополнить wiki~~

**Comment by lagroffe** [comment]
По поводу переноса кнопки AnalyzeMe внутри app направо - насколько это нужно? Имхо, текущий вариант навигации смотрится органичнее, чем с внезапно убежавшей в другое место AnalyzeMe.

**Comment by lagroffe** [comment]
[страница](https://github.com/lanit-tercom-school/analyzeme/wiki/Navigation)

**Comment by adavydenko** [comment]
Тогда давайте не переносить

**Comment by lagroffe** [comment]
Тогда закрывать?

**Comment by adavydenko** [comment]
Да.

**Comment by adavydenko** [comment]
Кстати. А [список URL адресов](https://github.com/lanit-tercom-school/analyzeme/wiki/REST-API) при этом нам не нужно менять? Ничего там съехать не может из-за изменения навигации?

**Comment by lagroffe** [comment]
Вообще все должно быть нормально, т.к. rest привязан к корневому адресу, запросы от адреса страниц не зависят.
Кстати, я поменяла url, но не переименовывала jsp. Это нужно сделать или всё равно, как они называются?

**Comment by lagroffe** [comment]
Не уверена насчет запросов rConf только, а остальные должны работать

**Comment by adavydenko** [comment]
jsp - лучше, чтобы совпадали.
По поводу rest-запросов - тогда их проревьювим после.
