### ISSUE TITLE
Привести стиль приложений к единому виду

### ISSUE THREAD

**Issue by adavydenko** [lanit-tercom-school/analyzeme#183]
☑ 1. Использовать одинаковые цвета для кнопок/фона/текста
☑ 2. Внешний вид меню максимально приблизить к angular-ному
☑ 3. Вид кнопок оставить как есть bootstrap + mdl
☑ 4. Использовать единые шрифты (описать на вики) - название + размер. За основу принимаем шрифты стартовой страницы

**Comment by maxim-yakupov** [comment]
Я же правильно понимаю, что на публичных страницах оставляем старые стили(кроме навигации)?

**Comment by adavydenko** [comment]
Да.

**Comment by adavydenko** [comment]
Обновить статус по задаче, если сделана - закрыть.

**Comment by maxim-yakupov** [comment]
https://github.com/lanit-tercom-school/analyzeme/wiki/HTML-Standards/ad4a1cdcc6eaeadfd08be7cd273ef264c1c0ded8
