### ISSUE TITLE
Данные для R-обработчиков

### ISSUE THREAD

**Issue by lagroffe** [lanit-tercom-school/analyzeme#184]
По #91.
Решить, нужно ли удалять из памяти R-обработчика появившиеся в ней перед и в процессе выполнения скрипта данные - они могут вызывать неожиданное поведение.

Например если сначала вызвать скрипт
x <- c(0, 3)
а потом случайно использовать переменную x в другом скрипте без её инициализации, другой скрипт отработает как корректный, хотя не должен.

С другой стороны, на этом можно попытаться оптимизировать загрузку данных из файла в память R-обработчика - делать это только при первом обращении к этому файлу - но тогда очистить только посторонние переменные будет достаточно сложно.

**Comment by adavydenko** [comment]
А если финализировать инстанс? Или такой возможности нет?

**Comment by lagroffe** [comment]
Инстанс чего именно?

**Comment by adavydenko** [comment]
того класса, который занимается выполнением скрипта

**Comment by lagroffe** [comment]
он единственный для каждого типа обработчика, и именно поэтому проблема и возникает - данные из предыдущих скриптов сейчас доступны при обращении к новым

**Comment by adavydenko** [comment]
статический что-ли? если так, то наверняка есть какой-нибудь метод shutdown или что-нибудь похожее..

**Comment by lagroffe** [comment]
shutdown нам не нужен, т.к. новый запуск R-обработчка займёт лишнее время. но просто очистить память - это легко, да. вопрос в том, делать это после выполнения каждого скрипта, или нет? да, потому что это понятное поведение, нет, потому что так можно добавить оптимизацию загрузки данных из файлов, чтобы не гонять их к обработчику много раз.

**Comment by adavydenko** [comment]
Думаю, что для чистоты расчетов данные нужно очищать. Вопрос оптимизации можно отдельно обсудить.
Кстати, если используется одно и то же рабочее пространство, не будет ли конфликтов в случае одновременного запуска скриптов? Предусмотрена ли автоматическая блокировка процесса в этом компоненте или это нужно делать вручную?

**Comment by lagroffe** [comment]
Хорошо, тогда добавлю очищение.

Будут, скорее всего, по крайней мере с Rserve. Для Renjin можно несколько изменить класс, который за него отвечает, и он справится сам, но вообще контроль за тем, чтобы несколько скриптов не отправлялись одному обработчику одновременно, предполагалось RScriptManager приписать
