### ISSUE TITLE
Проверка файла при загрузке

### ISSUE THREAD

**Issue by lagroffe** [lanit-tercom-school/analyzeme#202]
Сейчас предполагается, что пользователь загружает только поддерживаемые (пока один) типы файлов. 

Нужно обдумать и реализовать схему проверки того, что файл поддерживается нашей системой: формально проверять заданное расширение, а потом и само содержимое MultipartFile.

В рамках этой же задачи можно добавить автоматическое определение типа файла для его дальнейшей обработки, если это окажется несложно (один из заранее заданных вариантов, напр. вернуть информацию о том, json это или csv)

**Comment by lagroffe** [comment]
Частично выполнено (формальная проверка по указанному расширению), остальное очень имеет смысл вынести на лето.

**Comment by lagroffe** [comment]
Подразумевалось использование (к вопросу об отличии от парсера):
https://en.wikipedia.org/wiki/List_of_file_signatures
либо
https://ru.wikipedia.org/wiki/%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA_MIME-%D1%82%D0%B8%D0%BF%D0%BE%D0%B2

**Comment by KirillZubov** [comment]
Добавлена проверка файла по содержимому MultipartFile
