### ISSUE TITLE
Рефакторинг анализаторов

### ISSUE THREAD

**Issue by lagroffe** [lanit-tercom-school/analyzeme#207]
Изменить интерфейс анализаторов с работы с наборами двумерных данных на работу с одномерными векторами-колонками. 
Либо добавить для этого новый метод в интерфейсе и выкидывать исключения из неподдерживаемых вариантов, либо, пока не поздно, отредактировать готовые анализаторы для поддержки такого представления

**Comment by adavydenko** [comment]
//При исправлении не забыть обновить страницу на вики.

**Comment by lagroffe** [comment]
Скорее даже не обновить, а написать по [шаблону](https://github.com/lanit-tercom-school/analyzeme/wiki/Analyzers:-%5BTEMPLATE%5D). То, что есть сейчас, - только краткая теоретическая справка.

**Comment by lagroffe** [comment]
Анализаторам добавить поле о количестве параметров
Добавить в контроллер формирование данных для анализатора (пока по первым колонкам, потом будет выбираться на фронтенде)
