### ISSUE TITLE
Предложить систему логирования

### ISSUE THREAD

**Issue by adavydenko** [lanit-tercom-school/analyzeme#208]
Необходимо продумать ведение логов на сервере и общую обработку ошибок.
Необходимо найти и критически рассмотреть существующие фреймворки/приложения, позволяющие мониторить работу системы, предоставлять доступ в логам и т.д. и т.п.

Перед начало работы над задачей, составить список рассматриваемых продуктов.

- [x] добавить систему логирования
- [x] стиль логирования
- [x] добавить примеры логирования в нашем приложении

**Comment by adavydenko** [comment]
1) http://www.slf4j.org/ + logback
2) ??

**Comment by lagroffe** [comment]
Спасибо, я как раз рассматривала два из фреймворков, с которыми SLF4J работает, а сам его не видела

**Comment by lagroffe** [comment]
Добавила logback+papertails, для начала внутри приложения логируются переходы по страничкам. У Heroku есть немало своих логов, они отображаются там же: у наших (отмечены зелёными стрелками) немного другой формат
![2016-07-14_13-55-27](https://cloud.githubusercontent.com/assets/8055513/16837229/b6eccdf6-49ca-11e6-8789-c528e6c781b0.png)

**Comment by lagroffe** [comment]
Для просмотра логов нужно зайти на хероку и внутри приложения analyzeme-dev (вкладка Overview) кликнуть на Papertrail. 
Прямая ссылка https://papertrailapp.com/systems/analyzeme-dev/events, но не уверена, что будет так работать

**Comment by lagroffe** [comment]
Как использовать логгер - [wiki](https://github.com/lanit-tercom-school/analyzeme/wiki/%D0%9B%D0%BE%D0%B3%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-(Java))
