### ISSUE TITLE
Реализовать возможность задания пользовательских R-сценриев

### ISSUE THREAD

**Issue by adavydenko** [lanit-tercom-school/analyzeme#21]
В качестве пользователя проекта, мне было пригодилась возможность создавать пользовательские скрипты. Т.о. независимо от разработчиков сайта/системы, я мог бы проводить свой собственный анализ данных.

Для этих целей необходимо иметь он-лайн редактор и каким-то образом пополнять свою собственную, пользовательскую библиотеку функций над данными.

**Comment by lagroffe** [comment]
библиотека -> #156
