### ISSUE TITLE
Интеграция с R: шаблон для анализаторов

### ISSUE THREAD

**Issue by lagroffe** [lanit-tercom-school/analyzeme#232]
В рамках этой задачи создать:
- [x] "шаблоны" R скриптов для поддерживаемых значений на вход/выход:
 * как использовать данные из файлов
 * как возвращать значения из R
- [x] "шаблон" класса на Java - анализатора, который использует заготовленный скрипт на R
- [ ] отредактировать HelpPage для скриптов пользователя

**Comment by lagroffe** [comment]
плюс 
- [ ] отредактировать HelpPage для скриптов

**Comment by lagroffe** [comment]
Первый пункт - см. [wiki](https://github.com/lanit-tercom-school/analyzeme/wiki/R-scripts). 
Наши скрипты, удовлетворяющие нужным условиям, предлагаю сохранять в какую-нибудь папку в репозитории, и потом уже преобразовывать их в IAnalyzer

**Comment by adavydenko** [comment]
А HelpPage будете обновлять, если не требуется - то тогда удалите, пожалуйста, этот пункт из описания задачи.

**Comment by lagroffe** [comment]
47256e9 автоматически закрыл, пункт после отметила
