### ISSUE TITLE
Проработать архитектуру анализаторов

### ISSUE THREAD

**Issue by adavydenko** [lanit-tercom-school/analyzeme#25]
Необходимо проработать архитектуру классов для унифицированного анализа.

Например, было бы удобно вызывать вот так:
```
IAnalyzer min = AnalyzerFactory.Get("GlobalMin");
SingleResult res = min.Analyze(new int[]);
return res.value;
....
vs
GlobalMin x = new GloabMin();
int res = x.CalculateMin(new int[]);
return res;
```

**Comment by SKutukov** [comment]
https://github.com/lanit-tercom-school/analyzeme/wiki/Architecture-of-analize-function. 
страница на wiki

**Comment by adavydenko** [comment]
Добавьте диаграмму классов, для простоты восприятия. воспользоваться можно, например, вот этим сервисом - http://www.planttext.com/planttext
