### ISSUE TITLE
Завести gitbook по статистике

### ISSUE THREAD

**Issue by adavydenko** [lanit-tercom-school/analyzeme#260]

**Comment by x1o** [comment]
Прежде всего, нужен ли нам именно gitbook? Уже существующий текст перенести туда будет сложно, хоть gitbook и умеет математику (пусть с ограничениями по сравнению с полноценным ТеХ'ом). Я бы мог сконвертировать .tex в Markdown при помощи pandoc, но тогда потерялись бы все теховские окружения вроде теорем или определений, а для математического текста это все-таки существенно. Можно было бы вести две параллельных версии текста: одну полноценную и одну "облегченную", но это потребовало бы много ручной работы, как кажется, нецелесообразной.

Если нужна версионизация, то она есть[1] сейчас, правда на древнючем CVS :) (однако хватает его!)

Наверное, стоит прежде решить, как будет документироваться проект в принципе и затем предметно комментировать каждый кусочек. Кстати, думаю, что для такого проекта проблема документации действительно существенна, потому что сплошь и рядом народ пользуется статистикой абсолютно без понимания происходящего и приходит из-за этого, конечно, к выводам ошибочным.

1: http://cvs.ungrund.org/cvs/lecture_notes/Statistics/6/

**Comment by adavydenko** [comment]
Решили, что gitbook не нужен, т.к. 
1) не поддерживает мат. выражения
2) автоматически не сконвертировать в его формат.

**Comment by adavydenko** [comment]
Дополнительно по поставленным вопросам:
1. Версионированность не нужна
1. Документируем все через wiki + комментарии в исходниках. Имхо пока это единственный доступный формат. У нас есть шаблон описания - Analyzer, документацию по статистике можно вести в подобном же виде. Теоретически.

**Comment by x1o** [comment]
При добавлении новой версии документа по статистике в CVS-репозитарий на ungrund.org, отрендеренная pdf-ка автоматически компируется в [/doc/statistics-manual.pdf](https://github.com/lanit-tercom-school/analyzeme/blob/dev/doc/statistics-manual.pdf). Надеюсь, что сможем организовать хорошую документацию через wiki.
