### ISSUE TITLE
renjin + bioconductor repos

### ISSUE THREAD

**Issue by adavydenko** [lanit-tercom-school/analyzeme#265]
Проверить возмножость подключаться сторонние пакеты (в первую очередь интересует bioconductor.org: _snprelate_, ...

**Comment by kazuare** [comment]
Если я нигде не облажался в работе с кодом, то Renjin - это полный провал.
Сейчас обьясню, почему:
При подключении нужных jar файлов все подключается отлично, но проблема в том, что ничего не работает, gdsfmt не может даже файл открыть.
Это достаточно неудивительно, Renjin вроде использует свой движок для R, не успевающий за своим старшим братом по возможностям.
Дополню еще:
Вот тут (описание gdsfmt в renjin'е)
http://packages.renjin.org/package/org.renjin.bioconductor/gdsfmt
написано:
This package can be loaded by Renjin but there was an error compiling C/FORTRAN sources and all tests failed
Судя по надписи all tests failed, все очень плохо.
С остальными даже и пытаться не стоит, я думаю.
Закрываю, если никто не против.
