### ISSUE TITLE
Привязать вызов функции GlobalMax/Min к стартовой странице

### ISSUE THREAD

**Issue by SKutukov** [lanit-tercom-school/analyzeme#32]
* Привязать вызов функции GlobalMax/Min к странице #8.

**Comment by SKutukov** [comment]
При более подробном рассмотрении класса JsonParser, обнаружилось  что парсер требует строки вида {"x": ["1",  "2.5",  "4.7"],"y": ["5",  "6.5",  "7.7"]}, а при отображении данных  используются строки  вида [	{   "x": 1,        "y": 1   }, { "x": 20,   "y": 60 }, { "x": 40,  "y": 40  }].
Надо выбрать какие строки мы будем использовать.
Я склоняюсь ко второму варианту, так как d3.js больше заточен под такое представление данных.

**Comment by SKutukov** [comment]
Выпадающий список функций реализован в ветке ActionPage

**Comment by adavydenko** [comment]
Смержить в dev
