### ISSUE TITLE
Create build scripts

### ISSUE THREAD

**Issue by adavydenko** [lanit-tercom-school/analyzeme#4]
Необходимо разработать скрипты для сборки проекта локально в виде bat-файла или чег-нибудь другого.
Цель - чтобы каждый участник проекта смог из исходных кодов _достаточно легко_ собрать последнюю версию (без деплоя).

**Comment by adavydenko** [comment]
Добавить поддержку ubuntu

**Comment by lagroffe** [comment]
Поддержка Windows осуществляется, другие задачи вынесены на будущее - пока см. #38
