### ISSUE TITLE
Реализовать классы, связанные с хранением проектов (см.диаграмма)

### ISSUE THREAD

**Issue by lagroffe** [lanit-tercom-school/analyzeme#42]
![repository](https://cloud.githubusercontent.com/assets/8055513/13224829/5f400af4-d99b-11e5-9090-418c1f2a58b5.png)
+ добавить удаление проекта

**Comment by lagroffe** [comment]
При создании нового проекта генерировать код проекта, который потом будет входить в url

**Comment by lagroffe** [comment]
При регистрации пользователя генирировать число-идентификатор, который будет входить в url и использоваться для доступа

**Comment by lagroffe** [comment]
При удалении проекта реализовать удаление файлов, связанных с проектом, из основного репозитория

**Comment by adavydenko** [comment]
Обратите внимание, что удалять файлы можно только тогда, когда больше никто ими не пользуется.
Также предлагаю физически не удалять, а помечать проекты (и файлы) соответственно, как удаленные. Это можно делать по 2м причинам:
1. Пользователь может ошибиться и захотеть восстановить проект
2. Обычно операция удаления трудозатратнее для сервера чем обновление (блокировка таблиц, перестроение индексов и т.д.

**Comment by lagroffe** [comment]
Достаточно отмечать как удалённый только проект, или лучше добавить это поле в информацию о каждом файле?

**Comment by lagroffe** [comment]
(теоретически доступ к файлу должен происходить только по вертикали пользователь-проект-файл, т.е. если проект будет неактивен, доступ к файлу получить будет нельзя и без создания дополнительных полей в информации о нём)

**Comment by adavydenko** [comment]
Я думаю и так и так можно. Вдруг пользователь удалит файл, а потом его захочет восстановить.

**Comment by lagroffe** [comment]
За исключением возможных поправок, классы, необходимые для текущих задач, реализованы.

**Comment by lagroffe** [comment]
Новые диаграммы (plant-uml) см. [wiki](https://github.com/lanit-tercom-school/analyzeme/wiki/%D0%9F%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D0%B8,-%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D1%8B-%D0%B8-%D1%84%D0%B0%D0%B9%D0%BB%D1%8B)

**Comment by lagroffe** [comment]
[Страница на вики](https://github.com/lanit-tercom-school/analyzeme/wiki/%D0%9F%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D0%B8,-%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D1%8B-%D0%B8-%D1%84%D0%B0%D0%B9%D0%BB%D1%8B) обновлена для отражения всей системы классов-репозиториев
