### ISSUE TITLE
Сервлеты, обеспечивающие работу с проектами

### ISSUE THREAD

**Issue by lagroffe** [lanit-tercom-school/analyzeme#43]
Для обращения к проекту необходимы сервлеты/сервлет, которые будут по запросу со стороны JS обеспечивать:

1. Отображание списка проектов, доступен по адресу 
    /projects
    /projects/ - Создание нового проекта - pop-up, запрашивающий название
    /projects/ - подтверждение удаления (pop-up)
   
2. Добавление файлов в проект
3. Отображение списка файлов, доступных в проекте; 
    /projects/{name} -  работа с существующим проектом
4. Обработку запросов, связанных с использованием уже загруженных файлов.

**Comment by lagroffe** [comment]
1. UploadServlet now upload files for default user "guest" in the project "default" (change if request from js changes)
2. CreateProjectServlet & DeleteProjectServlet now work for projects for user "guest" (change if users added)
3. GetFilesInProjectServlet & GetProjectNamesServlet - base for real servlets (other issues) to show how to use repositories

**Comment by lagroffe** [comment]
- ReturnProjectsInfoServlet returns json array of json objects with:

		- projectName (in Java - String)
		- login (in Java - String)
		- lastChangeDate (in Java - Date)
		- projectId (in Java - String)

		to use for all projects page and link for one project page
- DeleteFileServlet and DeleteProjectServlet does not delete files and projects completely, just deactivates them. (If DeleteProjectServlet was called, files in project will be deactivated too)

**Comment by lagroffe** [comment]
- CreateProjectServlet - Get-request with header "projectName". Returns response with header "Success" ("project was not created") or "projectId" (unique (for user) name of the project)

- DeleteFileServlet - Get-request with header "filename". Returns response with header "Success" ("file deleted" or "file not deleted"). Now this servlet deactivates the file, not erases it.

- DeleteProjectServlet - Get-request with header "projectName". Returns response with header "Success" ("project deleted" or "project not deleted"). Now this servlet deactivates the project, not erases it.

- GetFilesInProjectServlet - Get-request with header "projectName". Returns response with header "Success" (json of strings with unique filenames)

- GetProjectsNamesServlet - Get-request. Returns response with header "ProjectNames" (json with strings)

- ReturnProjectsInfoServlet (for issue #54) - Get-request. Returns response with header "Success" (array of json objects with nec.info)

**Comment by adavydenko** [comment]
Подготовьте к следующему разу код-ревью пожалуйста.

**Comment by lagroffe** [comment]
А можно чуть подробнее, в каком виде?

**Comment by adavydenko** [comment]
Давайте на бумаге. Если у вас есть где распечатать, то сделайте 2-3 копии, если нет - пришлите мне текстовый файл для печати, я сделаю.

**Comment by lagroffe** [comment]
Хорошо, принесу. Именно эту задачу или репозитории? В сервлетах логики две-три строчки

**Comment by lagroffe** [comment]
Для текущих задач все сервлеты реализованы
