### ISSUE TITLE
Реорганизовать структуру папок

### ISSUE THREAD

**Issue by adavydenko** [lanit-tercom-school/analyzeme#44]
?. Убрать бинарники из репозитория
1. Конечная структура папок:
./src/main/java/com/analyzeme/..
  ../controllers/
  ../repository/
./src/main/webapp/..

**Comment by lagroffe** [comment]
Папки с бинарными файлами из всех веток удалены. 
Папки и соответствующие package переименованы, mvc-dispatcher-servlet исправлен.

Есть вопрос, нужна ли ещё ветка StartPage(WorkPage)?

**Comment by adavydenko** [comment]
если все перенесли, то думаю, что и не нужна уже больше. При необходимости - можно будет создать новый бранч.
