### ISSUE TITLE
Стартовая форма должна работать с текущим проектом

### ISSUE THREAD

**Issue by adavydenko** [lanit-tercom-school/analyzeme#56]
Необходимо переделать стартовую форму, чтобы она работала с содержимым определенного проекта:
1. Загрузка новых файлов должна производиться в текущий проект
2. Шапка формы должна содержать информацию о проекте

Форма должна быть доступна по адресу __/projects/{project_id}/__

**Comment by olga-muravjova** [comment]
я сделала ProjectViewController в котором есть два метода для загрузки action.html
1) "/project/demo" - просто загрузка страницы action
2) "/project/{project_id}" - загружает страницу action и передает в качестве параметра String projectId

**Comment by adavydenko** [comment]
отлично, то что нужно
