### ISSUE TITLE
Отображение списка файлов на форме проекта

### ISSUE THREAD

**Issue by adavydenko** [lanit-tercom-school/analyzeme#57]
1. Добавить список с названиями файлов слева
2. При выборе файла, он должен отобразиться на графике
3. Дальнейшие операции (напр. определение минимумов) проводятся с выбранным файлом.
4. При загрузке нового файла - список пополняетя.

**Comment by SKutukov** [comment]
Есть вопрос. Что делать если загружается файл с уже существующим именем. Не добавлять новый файл в список или добавлять его с индексом?Скорее надо бы подумать будем ли мы допускать загрузку файла, чьё имя совпадает с  уже существующим?

**Comment by adavydenko** [comment]
Если загружается файл с уже существующим именем в рамках проекта, то необходимо спрашивать пользователя, хочет ли он его заменить, или загрузить копию. Соответственно,:
* в одному случае - заменяем имеющийся файл, 
* во втором - меняем имя при загрузке.

Начать можно с 1-го.

**Comment by adavydenko** [comment]
Решили позволять загружать файлы с одинаковыми именами.
Если это сделано - закрыть.

**Comment by SKutukov** [comment]
Реализовано в ветке ActionPage

**Comment by adavydenko** [comment]
Смержить в dev
