### ISSUE TITLE
Провести лекцию по Angular.js

### ISSUE THREAD

**Issue by adavydenko** [lanit-tercom-school/analyzeme#58]
Рассказать:
 - Что из себя представляет разработка на Angular2 (1/2 лекции)
 - О прототипе приложения

**Comment by maxim-yakupov** [comment]
Добавлена вики-страница 'Angular 2 in JavaScript'
https://github.com/lanit-tercom-school/analyzeme/wiki/Angular-2-in-JavaScript

**Comment by maxim-yakupov** [comment]
Добавлена вики-страница 'Tour of Heroes tutorial in JavaScript'
https://github.com/lanit-tercom-school/analyzeme/wiki/Tour-of-Heroes-tutorial-in-JavaScript
