### ISSUE TITLE
R-facade

### ISSUE THREAD

**Issue by adavydenko** [lanit-tercom-school/analyzeme#63]
Необходим набор классов - фасад - предназначенных для перенаправления вызовов из сервлетов в R "engine"

**Comment by lagroffe** [comment]
Добавлены базовые интерфейсы для взаимодействия с R, есть вопрос по поводу значения, возвращаемого после вызова скрипта или команды.
Сейчас мы предполагаем, что получать будем какие-то данные для отрисовки, т.е. оптимальное возвращаемое значение - строка с json-объектами. В будущем возможно появление каких-то изображений/других файлов. Возвращаемые значения пока делать строками, или сразу добавлять стримы?

**Comment by adavydenko** [comment]
Из фасада R должны возвращаться массивы (и соответственно на вход должны подаваться массивы). Конвертация из/в json должна производиться вне фасада отдельно.

**Comment by lagroffe** [comment]
Оставляет вопрос по поводу возможно возвращаемых файлов.

Названия заменяемы, но сейчас разделение сделано так: 
- R.facade - принимает скрипт или команду, проверяет, какие данные нужно добавить для вызова, ищет их, преобразует в какой-то стандартный вид и передаёт в R.call. Результаты работы его потом преобразует, опять же, в какой-то стандартный вид. Это можно назвать каким-нибудь предфасадом, а R.call - фасадом, но суть не изменится.
- R.call - реальный вызов R через RServe или JRI. Ему как раз имеет смысл передавать массив.
Но вообще это ещё зависит от того, какой вариант выберем: с RServe может быть удобнее отдельно отправлять файлы и скрипты бэкэнду R, а потом просто вызывать скрипт (если это файлы, с которыми R сам умеет работать). С JRI все вызовы точно будут происходить где-то в R.call, т.е. как раз в этом случае данные должны подаваться массивом. Привязывать к проекту непосредственный вызов я только начала и думаю попробовать оба варианта, поэтому пока про более удобный формат данных между R.facade и R.call ничего сказать не могу, но вопрос не в нём - самый внешний результат работы сделать json-строкой/массивом (только для данных для отрисовки) или стримом (чтобы, в случае чего, иметь возможность возвращать файлы)?

**Comment by adavydenko** [comment]
json должен формироваться на последнем этапе, когда данные передаются через веб. Т.е. в контроллере/сервлете.
R.facade должен работать с моделью предметной области (например наше внутреннее представление данных), а R.call - с данными пригодным для передачи дальше в JRI/RServer/..whateveRelse.

Общепринятое назначение facade-а - предоставить простой интерфейс использования для конечного пользователя. Поэтому вся логика по преобразованию данных, вызову правильной последовательности команд, создания объектов и пр. должна содержаться внутри R.facade.

Еще один хороший паттерг - класс должен возвращать и принимать данные одного уровня абстракции. Так, например, если мы передаем классу double[], то возращать сформированную строку json не надо.
Это справедливо до тех пор, пока у нас специально не разделяются маршруты на вход/выход (т.е. пока нет чего-то вроде CQRS паттерна). Но нам это сейчас и не нужно, имхо.

**Comment by lagroffe** [comment]
R.facade.RFacade, за исключением создания объекта, отвечающего за реальную интеграцию, реализован, см. ветка [RinJava](https://github.com/lanit-tercom-school/analyzeme/tree/RinJava/src/main/java/com/analyzeme/R).
В будущем можно либо обращаться прямо к нему, либо, для более приятного вида функций, создавать объект одного из классов:
	1. R.analyze.RAnalyzerToGetNumber
	2. R.analyze.RAnalyzerToGetPoint
	3. R.analyze.RAnalyzerToGetPoints
	4. R.analyze.RAnalyzerDefault (в случае, если тип возвращаемого значения неизвестен. будет получать результат работы R в Object или что-то вроде с принудительным преобразованием, потом принудительно же пытаться определить, что ему вернулось, и формировать json. использовать рекомендуется только в крайних случаях, ошибки почти гарантированы)

К созданию - парсеры и классы, отвечающие за реальную интеграцию (должны реализовывать R.call.IRCaller), см.новые issue.

После обсуждения и корректировки задачу, связанную с фасадом, можно закрывать.
