### ISSUE TITLE
Исследовать возможность набора R команд в браузере

### ISSUE THREAD

**Issue by adavydenko** [lanit-tercom-school/analyzeme#64]
Найти готовый js (или иной) редактор исходного код на R.
При выборе редактора обратить внимание на то, каким образом в него передавать входные данные для анализа.
Попробовать реализовать найденные варианты.

или убедиться, что их нет :(

**Comment by maxim-yakupov** [comment]
Вариант: Ace-editor https://habrahabr.ru/post/230749/

**Comment by SKutukov** [comment]
Страница на Wiki про Ace-editor
https://github.com/lanit-tercom-school/analyzeme/wiki/Ace-editor
