### ISSUE TITLE
Найти java-библиотеку для работы с excel

### ISSUE THREAD

**Issue by adavydenko** [lanit-tercom-school/analyzeme#77]
Базовые функции:
* Извлекать данные по наименованию колонки
* Конвертировать/или получать информацию о типах данных
* Получить информацию о количестве колонок и их названия

Результат выполнения задачи - набор рассмотренных библиотек, для выбранной - пример использования

**Comment by lagroffe** [comment]
Парсер (функция, обращающаяся к найденной библиотеке) добавлять в https://github.com/lanit-tercom-school/analyzeme/tree/dev/src/main/java/com/analyzeme/parsers
Затем создать
SourceInfo для excel файлов в https://github.com/lanit-tercom-school/analyzeme/tree/dev/src/main/java/com/analyzeme/data/resolvers/sourceinfo
Затем добавить в https://github.com/lanit-tercom-school/analyzeme/blob/dev/src/main/java/com/analyzeme/repository/filerepository/FileUploader.java
Если ещё не добавлена проверка #202, добавить if в FileController
