### ISSUE TITLE
Парсер R

### ISSUE THREAD

**Issue by lagroffe** [lanit-tercom-school/analyzeme#87]
Создать парсер, который будет принимать
  * команды (в виде строк)/скрипты (стримы с данными из файла) на R
  * id пользователя
  * id проекта  

и возвращать
  * набор id файлов с данными, необходимыми для выполнения скрипта/команды

Предполагается, что в скрипте пользователь использует начальное имя файла, загруженного в рамках текущего проекта

**Comment by adavydenko** [comment]
При реализации, добавить примера такого R скрипта

**Comment by lagroffe** [comment]
Также необходимы отдельные парсеры или отдельные функции в этом парсере для интеграций, которые будут обеспечивать непосредственное "подсовывание" данных при вызове: определение места использования, подстановка (для использования массивов данных), какая-то замена пользовательских функций или их аргументов (для использования файлов).

**Comment by lagroffe** [comment]
В простейшем варианте (первом к реализации) пользователь будет обращаться с данными из файла:
- либо как с парой векторов (как если бы каждый из них был задан через `x <- c(someValues)`, `y <- c(someValues)`)
- либо как с dataframe из x и y (аналог создания в R: `coords <- data.frame(x = c(someValues), y = c(someValues)`)

//предполагается выбрать один
Сам пользователь их создание не задаёт, используя вместо этого удобный для парсинга стандарт именования (рассмотреть, например, вариант : x_myData_, y_myData_ для векторов с данными x и y из файла myData. желательно, чтобы именование не вызывало каких-то неприятных вещей в стандартной подсветке R-синтаксиса).
Задача RParserа в таком случае - только обнаружить использование подобных переменных и вернуть список файлов, данные из которых нужны для работы скрипта.

**Comment by adavydenko** [comment]
А в чем разница при использовании одного и второго подхода?
По поводу синтаксиса - я думаю, что можно использовать нестанадартный, но сделать так, чтобы редактор особым образом выделял именно наши переменные - это будет требованием к редактору. Плюсы подхода - код изнаально невалидный, и это хорошо.
Если таких возможностей у редактора нет, то будет придумывать наименования, корректные с точки зрения R.

**Comment by lagroffe** [comment]
В том, что сказать пользователю о том, как писать скрипт - а так неважно. Использовать вектора при подстановке несколько удобнее, но несущественно.

Просто корректное именование переменных для R в первом случае тоже придётся придумать, для исполнения скрипта. Если парсеру будет удобнее искать именно невалидные - хорошо, но тогда перед передачей скрипта в R.Call их нужно будет заменить на какие-то верные. Но это, если будет корректно работать их поиск в тексте, будет уже достаточно несложно, а особые обозначения - это полезно, так что если редактор позволит, вполне вариант.

**Comment by adavydenko** [comment]
Мы можем ввести правило, например такое:
```R
#MyData.x#  + #MyData.y#:
MyData < data.frame(x = c(someXvalues), y = c(someYvalues))
```

**Comment by lagroffe** [comment]
Не совсем поняла, в чём идея) Если в том, чтобы объединить оба способа, то там дело ещё в том, как они дальше будут использоваться в скрипте. Обращение к элементу в векторе и data.frame разное, например. 
Т.е. при таком варианте с подстановкой данных из файла нужно перед написанием скрипта сказать, в каких структурах данных лежат точки, чтобы пользователь использовал именно эту структуру.

А если чисто по именованию, то я посмотрю на выходных побольше о том, как вообще можно реализовать в нашем случае парсер, и предложу несколько вариантов - обсудим потом то, насколько они согласуются с редактором.

**Comment by lagroffe** [comment]
Наверное, лучше всё-таки делать именование переменных изначально валидным. Особая подсветка синтаксиса, если будет, скорее всего будет задаваться регулярным выражением или чем-то около, а ему всё равно, валидно ли написанное в языке. И если парсинг текста только с целью извлечь нужные имена файлов - очень лёгкая задача, то заменять переменные на какие-то правильные будет сложнее.

**Comment by adavydenko** [comment]
Надо обсудить на встрече. Напомните, пожалуйста.
