### ISSUE TITLE
Классы, обеспечивающие интеграцию с R

### ISSUE THREAD

**Issue by lagroffe** [lanit-tercom-school/analyzeme#91]
Необходимы классы, реализующие интерфейс R.call.IRCaller (см. [RinJava](https://github.com/lanit-tercom-school/analyzeme/tree/RinJava/src/main/java/com/analyzeme/R)). Предположительные варианты используемых средств интеграции - RServe и ~~JRI~~.
Текущая задача: реализовать простейшие функции runCommandToGetNumber(String rCommand, String jsonData), не требующие для своего выполнения существования каких-либо парсеров.
//функции, работающие с jsonData, сделаны потому, что, по сути, сейчас именно это наше представление данных для хранения - функции, работающие с файлами, будут им во многом аналогичны

**Comment by lagroffe** [comment]
Также рассмотреть вариант, использующий не отдельный R, а JVM - например [Renjin](http://www.renjin.org/)

**Comment by lagroffe** [comment]
Реализованы простейшие функции для Rserve и Renjn: для одного файла одна команда. 

При реализации считается, что файл содержит точки с координатами x и y, обращение к ним - как к двум векторам R (аналогично одномерным массивам Java), возвращаемое значение - `double`. Примеры поддерживаемых команд:

+ `mean(x)`
+ `y[3]`
+ `mean(y)+x[0]`
+ ...

**Comment by lagroffe** [comment]
Rserve на данный момент работает только локально, для подключения к Heroku необходим отдельный сервер для R. Renjin проверен на Heroku, работает.

**Comment by adavydenko** [comment]
(не понял, что реализовано)

**Comment by lagroffe** [comment]
Можно обратиться по url `/RserveCommand/{filename}/{Rcommand}` или `/RenjineCommand/{filename}/{Rcommand}`, где filename - имя любого загруженного файла, а Rcommand - одиночная команда на R, использующая данные из этого файла и возвращающая double. Url пока сделано чисто для ручных тестов, потом это естественно будет выглядеть не так, а другие возвращаемые значения будут в ближайшее время. Пока суть была в основном в том, чтобы проверить, как поведут себя в проекте средства интеграции

**Comment by adavydenko** [comment]
Понятно, т.е. это своего рода API для вызова уже готовых команд. Ок.

**Comment by lagroffe** [comment]
Реализованы функции, работающие с командой-строкой и json-строкой вида: `{"Data":[{ "x": "1","y": "1" },{"x": "20","y": "20"}]}` (стандартный сейчас формат файлов). 

Теоретически для реализации функций, использующих данные из файлов, необходима некоторая структура, которая будет содержать информацию о "колонках" данных (для точек, например, названия "x" и "y") - видимо, связанная с #118 или ещё не поставленными задачами.
@adavydenko Реализовать пока для нынешнего формата файлов, или сначала заняться бэкендом для Rserve?

**Comment by lagroffe** [comment]
Классы, отвечающие непосредственно за интеграцию, для текущих типов данных реализованы, залиты в dev. Unit-тесты для них написаны, проходят.
