### ISSUE TITLE
Настройки системы

### ISSUE THREAD

**Issue by adavydenko** [lanit-tercom-school/analyzeme#95]
Необходимо добавить страницу настроек:
1.~~Сделать на нее ссылку из главного меню~~
2. ~~Создать контроллеры и репозиторий настроек~~
3. Выбор текущего обработчика R
4. Сохранять настройки для R.Caller-ов:
 - Rserve (порт, хост)
 - FakeR (см #96 )

**Comment by adavydenko** [comment]
Настройки нужно хранить в памяти, firebase не ипользуем пока.

**Comment by adavydenko** [comment]
Выделили задачи #119, #120, #121, #122

**Comment by adavydenko** [comment]
#120, #121, #122 не закрыты - перевожу на future

**Comment by SKutukov** [comment]
#120, #121, #122  закрыты
