### ISSUE TITLE
FakeR

### ISSUE THREAD

**Issue by adavydenko** [lanit-tercom-school/analyzeme#96]
Реализовать мок объект, имитирующий работу с R бэкендом.

**Comment by lagroffe** [comment]
Вариант, возвращающий дефолтные значения - `""` для String, `0` для double, `new Point()` для Point, `new ArrayList<Point>()` для List<Point> - реализован, см. [R.call.FakeR](https://github.com/lanit-tercom-school/analyzeme/blob/RinJava/src/main/java/com/analyzeme/R/call/FakeR.java)
