### ISSUE TITLE
How to deploy on Heroku

### ISSUE THREAD

**Issue by adavydenko** [lanit-tercom-school/analyzeme#98]
1. Провести workshop как опубликовать свой бранч на Heroku
2. Выложить инструкцию в wiki

**Comment by lagroffe** [comment]
[Инструкция в wiki](https://github.com/lanit-tercom-school/analyzeme/wiki/Heroku). 
Workshop будет нужен? Там, вообще говоря, ничего хоть сколько-то сложного.

**Comment by adavydenko** [comment]
Мне понравилось, как описано. Давайте на встрече пробежимся по нему.
